name: precheck_image
description: "A new Flutter plugin project."
version: 0.0.1
homepage: "https://github.com/Yoga3911/precheck_image_channel"

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.pakektp.precheck_image
        pluginClass: PrecheckImagePlugin
